### PR TITLE
Release 0.15.0

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
We should probably add a  `pin_run_as_build` or `run_exports ` section to the recipe.

Maybe something like

```yaml
pin_run_as_build:
  cppzmq: x.x
  nlohmann_json: x.x
  xtl : x.x
```

The idea is that

- xeus does *not* depend on these header-only packages at runtime.
- however, , even though `cppzmq`, `xtl` and `nlohmann_json` are header-only, downstream packages like xeus-cling have *runtime* dependency on them, (they are used at runtime by the C++ interpreter), and this should be *pinned* to what is used at build time for xeus and xeus-cling.

**Comment by SylvainCorlay** [comment]
@conda-forge-admin please rerender

**Comment by SylvainCorlay** [comment]
Resources:

https://github.com/conda/conda-build/wiki/Migrating-numpy-x.x-to-Conda-build-3's-pin_run_as_build
https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/102
https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#export-runtime-requirements

**Comment by minrk** [comment]
I'd have to test to make sure this all comes out right, but to have xeus pin but not require, you may want to use [run_constrained](https://github.com/conda/conda/issues/1696#issuecomment-300309736).

Here's what I would try:

```yaml
# xeus
requirements:
  build:
    - cppzmq  # free at build time
  run_constrained:
    - {{ pin_compatible("cppzmq") }}
````

and downstream:

```yaml
requirements:
  build:
    - xeus
    - cppzmq # this cppzmq will be pinned by run_constrained above
  run:
    - cpppzmq # this will be pinned by pin_run_as_build below

# downstream conda_build_config.yaml
pin_run_as_build:
  - cppzmq: "x.x"
```

What this should do:

- xeus pulls in cppzmq as a build dependency. The version of this package is recorded.
- xeus has a "run_constrained" requirement, which is not a dependency, but a pinning of cppzmq *if*  cppzmq and xeus are to be installed in the same env.
- downstream has a build dependency on xeus, cppzmq. This is where the run_constrained in xeus gets applied, and ensures that the cppzmq in the build env is the version pinned by xeus at its own build time.
- downstream has pin_run_as_build applied, which syncs the versions from its own build env to its runtime deps, propagating the pinning from the xeus build-time.

**Comment by SylvainCorlay** [comment]
Thanks @minrk! I was adding a comment from my understanding

which was to add:
> ```yaml
> run_constrained:
>     - {{ pin_compatible('xtl') }}
>     - {{ pin_compatible('nlohmann_json') }}
>     - {{ pin_compatible('cppzmq') }}
> ```

From your message, I understand that `xtl`, `nlohmann_json`, and `cppzmq` need to be added to build in addition to host?

**Comment by minrk** [comment]
I think you can additionally get rid of the `pin_run_as_build` in downstream packages if you use `run_exports` on packages like `cppzmq`. default run_exports are only inherited by packages where the dependency is a "host" dependency. So:

cppzmq:

```yaml
build:
  run_exports:
    - {{ pin_subpackage('cppzmq', max_pin='x.x') }}
```

xeus:

```yaml
requirements:
  build:
    - cppzmq # doesn't get runtime dependnecy because this is 'build' not 'host'
  run_constrained:
    - {{ pin_compatible("cppzmq") }}
```

downstream:

```yaml
requirements:
  host:
    - xeus
    - cppzmq # will get exported, pinned cppzmq as a runtime dependency
```

**Comment by minrk** [comment]
> From your message, I understand that xtl, nlohmann_json, and cppzmq need to be added to build in addition to host?

No, they should go in whichever is appropriate for build or host (probably host). The important thing is that the constraint gets applied when xeus and cppzmq are installed together.

**Comment by SylvainCorlay** [comment]
Gotcha, thanks!

Regarding the requirement to add `run_exports` to `cppzmq`, is it necessary even if we assyme that cppzmq follows semver?

The `pin_subpackage` appears to be for subpackages right?

**Comment by minrk** [comment]
> Regarding the requirement to add run_exports to cppzmq, is it necessary even if we assyme that cppzmq follows semver?

Yes. conda doesn't implicitly add version pinnings, only those you ask it to. So if you express a dependency on `xeus` it's a fully free dependency on any version of that package.

So:

```yaml
build:
  run_exports:
    - {{ pin_subpackage('cppzmq', max_pin='x') }}
```

is they way to express that the current package (cppzmq) practices semver, and packages built against cppzmq 1.2.1 should have a runtime dependency on cppzmq 1.2.1 <= v < 2 (or 1.3 if you use max_pin='x.x'). If you don't specify run_exports, packages built against cppzmq will not have any runtime dependency or pinning other than what you explicitly add to the downstream meta.yaml.

> The pin_subpackage appears to be for subpackages right?

It's for any package being built in the current recipe.

**Comment by SylvainCorlay** [comment]
So I added a `run_exports` section to xeus, so that xeus becomes a runtime dependency of whatever it is a host-time dependency of.

**Pull request merged**
